apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: fase5-video-notification-worker
spec:
  serviceAccountName: fase5-video-notification-worker-service-account
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command: ['sh', '-c', 'sleep 3600']
  restartPolicy: Never
x
