apiVersion: v1
kind: Service
metadata:
  name: fase5-video-notification-worker-service
  namespace: fase5-video-notification-worker
spec:
  selector:
    app: fase5-video-notification-worker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
