apiVersion: v1
kind: ServiceAccount
metadata:
  name: fase5-video-notification-worker-service-account
  namespace: fase5-video-notification-worker
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::814147156565:role/fase5-video-notification-worker-iam-role
